# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb2909d795d54f680a87838cc4b816b6300e916d5a23abd5e16142a652795b45dbc4b351385d244206d3f72a3bab88945ac1cbe4ccffb910931cfc2e2b4f2b24

test:
  secret_key_base: 31ea4583f50ee633b39b48ce92ae20c9b3b8dbba1517009d0ff3f4dc9cc8ea16506d96a10aa3ea8d8277b7ca1ce31b14705483b905e55ea716c58526f70f7778

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
